[package]
name = "tortue-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
tortue = { path = "../" }

[[bin]]
name = "circle"
path = "src/circle.rs"

[[bin]]
name = "square"
path = "src/square.rs"
